import { Octokit } from '@octokit/rest';

const octokit = new Octokit({ auth: process.env.GITHUB_TOKEN });

export async function createDocsPR(docsRepo, docs, sourcePRs) {
  const [owner, repo] = docsRepo.split('/');
  const branch = `docs-sync-${Date.now()}`;

  // Get default branch
  const { data: repoData } = await octokit.repos.get({ owner, repo });
  const defaultBranch = repoData.default_branch;

  // Get latest commit SHA
  const { data: ref } = await octokit.git.getRef({ owner, repo, ref: `heads/${defaultBranch}` });
  const baseSha = ref.object.sha;

  // Create branch
  await octokit.git.createRef({ owner, repo, ref: `refs/heads/${branch}`, sha: baseSha });

  // Build content
  const content = [
    '# Documentation Updates\n',
    `*Auto-generated from ${sourcePRs.length} merged PR(s)*\n`,
    ...docs.map(d => `\n---\n\n### ${d.section}\n\n${d.content}\n\n> Source: ${d.source_pr}`),
  ].join('\n');

  // Create/update file
  const path = `updates/${new Date().toISOString().slice(0, 10)}-sync.md`;

  await octokit.repos.createOrUpdateFileContents({
    owner, repo, path, branch,
    message: `docs: auto-sync from ${sourcePRs.length} source PR(s)`,
    content: Buffer.from(content).toString('base64'),
  });

  // Create PR
  const { data: pr } = await octokit.pulls.create({
    owner, repo,
    title: `docs: cross-repo sync (${sourcePRs.length} source PRs)`,
    body: [
      '## Auto-generated documentation update\n',
      'Source PRs:',
      ...sourcePRs.map(p => `- [${p.repo}#${p.number}](${p.url}) — ${p.title}`),
      '\n---\n*Generated by [copilot-cross-repo-docs](https://github.com/jrubiosainz/copilot-cross-repo-docs)*',
    ].join('\n'),
    head: branch,
    base: defaultBranch,
  });

  return pr.html_url;
}
